ClassDemo/Controllers/ItemCategoryController.cs
using ClassDemo.Context;
using ClassDemo.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClassDemo.Controllers
{
    public class ItemCategoryController : Controller
    {
        ProjectManagementDbContext db = new ProjectManagementDbContext();
        public ActionResult ItemCategoryView()
        {           
            using (var _dbContext = new ProjectManagementDbContext())
            {
                var itms = _dbContext.ItemCategories.ToList();
                return View(itms);
            }
        }
        [HttpPost]
        public ActionResult ItemCategoryView(ItemCategory cat )
        {
            if (ModelState.IsValid)
            {
                db.ItemCategories.Add(cat);
                db.SaveChanges();
                return RedirectToAction("ItemCategoryView");
            }
            return View();
        }
        public ActionResult Delete(int id)
        {
            ItemCategory cat = db.ItemCategories.Find(id);
            db.ItemCategories.Remove(cat);
            db.SaveChanges();
            return RedirectToAction("ItemCategoryView");
        }
        public ActionResult Edit(int id)
        {
            ItemCategory cat = db.ItemCategories.Find(id);
            return View(cat);
        }
        [HttpPost]
        public ActionResult Edit(ItemCategory cat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ItemCategoryView");
            }
            return View(cat);
        }

    }
}

ClassDemo/Controllers/ItemPriorityController.cs
using ClassDemo.Context;
using ClassDemo.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClassDemo.Controllers
{
    public class ItemPriorityController : Controller
    {
        ProjectManagementDbContext db = new ProjectManagementDbContext();
        public ActionResult ItemPriorityView()
        {
            ItemPriority prio = new ItemPriority();
            return View(db.ItemPriorities.ToList());
        }
        [HttpPost]
        public ActionResult ItemPriorityView(ItemPriority prio)
        {
            if (ModelState.IsValid)
            {
                db.ItemPriorities.Add(prio);
                db.SaveChanges();
                return RedirectToAction("ItemPriorityView");
            }
            return View();
        }
        public ActionResult Edit(int id)
        {
            ItemPriority prio = db.ItemPriorities.Find(id);
            return View(prio);
        }
        [HttpPost]
        public ActionResult Edit(ItemPriority prio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ItemPriorityView");
            }
            return View(prio);
        }
        public ActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                ItemPriority pri = db.ItemPriorities.Find(id);
                db.ItemPriorities.Remove(pri);
                db.SaveChanges();
                return RedirectToAction("ItemPriorityView");
            }
            return View();
        }
    }
}

ClassDemo/Controllers/ItemStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClassDemo.Context;
using ClassDemo.Models;
using System.Data.Entity;

namespace ClassDemo.Controllers
{
    public class ItemStatusController : Controller
    {
        ProjectManagementDbContext db = new ProjectManagementDbContext();
        public ActionResult ItemStatusView()
        {
            ItemStatus stat = new ItemStatus();
            return View(db.ItemStatuses.ToList());
        }
        [HttpPost]
        public ActionResult ItemStatusView(ItemStatus stat)
        {
            if(ModelState.IsValid)
            {
                db.ItemStatuses.Add(stat);
                db.SaveChanges();
                return RedirectToAction("ItemStatusView");
            }
            return View();
        }
        public ActionResult Delete(int id)
        {
            ItemStatus stat = db.ItemStatuses.Find(id);
            db.ItemStatuses.Remove(stat);
            db.SaveChanges();
            return RedirectToAction("ItemStatusView");
        }
        public ActionResult Edit(int id)
        {
            ItemStatus stat = db.ItemStatuses.Find(id);
            return View(stat);
        }
        [HttpPost]
        public ActionResult Edit(ItemStatus stat)
        {
            db.Entry(stat).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("ItemStatusView");
        }
    }
}

ClassDemo/Controllers/ItemTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClassDemo.Context;
using ClassDemo.Models;
using System.Data.Entity;

namespace ClassDemo.Controllers
{
    public class ItemTypeController : Controller
    {
        ProjectManagementDbContext db = new ProjectManagementDbContext();
        public ActionResult ItemTypeView()
        {
            ItemType it = new ItemType();
            return View(db.ItemTypes.ToList());
        }
        [HttpPost]
        public ActionResult ItemTypeView(ItemType it)
        {
            if(ModelState.IsValid)
            {
                db.ItemTypes.Add(it);
                db.SaveChanges();
                return RedirectToAction("ItemTypeView");
            }
            return View();
        }
        public ActionResult Delete(int id)
        {
            ItemType it = db.ItemTypes.Find(id);
            db.ItemTypes.Remove(it);
            db.SaveChanges();
            return RedirectToAction("ItemTypeView");
        }
        public ActionResult Edit(int id)
        {
            ItemType it = db.ItemTypes.Find(id);
            return View(it);
        }
        [HttpPost]
        public ActionResult Edit(ItemType it)
        {
            db.Entry(it).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("ItemTypeView");
        }
    }
}

ClassDemo/Views/Shared/_Layout.cshtml
@using ClassDemo.Controllers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="~/Scripts/validation.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="../Home/Index.cshtml">
                    <img src="~/Content/Images/Logo2.png" style="margin-top:-3px;height:30px;" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Create Item", "CreateItem", "Home")</li>
                    <li>@Html.ActionLink("View Items ", "ItemsList", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Masters <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Item Categories", "ItemCategoryView", "ItemCategory")</li>
                            <li>@Html.ActionLink("Item Priority", "ItemPriorityView", "ItemPriority")</li>
                            <li>@Html.ActionLink("Item Type", "ItemTypeView", "ItemType")</li>
                            <li>@Html.ActionLink("Item Status", "ItemStatusView", "ItemStatus")</li>
                            <li>@Html.ActionLink("Project", "ProjectView", "Project")</li>
                            <li>@Html.ActionLink("New Registeration", "Registration", "Registration")</li>
                        </ul>
                </ul>
                <ul class="nav navbar-nav" style="float:right;">
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">admin<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("My Profile", "Details", "Registration")</li>
                            <li>@Html.ActionLink("Log Out", "Index", "Registration")</li>
                        </ul>
                    </li>               
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - COETL</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

ClassDemo/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="~/Scripts/validation.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="../Registration/Index.cshtml">
                    <img src="~/Content/Images/Logo2.png" style="margin-top:-3px;height:30px;" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Registration")</li>
                    <li>@Html.ActionLink("About", "About", "Registration")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Registration")</li>
                    <li>@Html.ActionLink("View Items", "Login", "Registration")</li>
                </ul>
                    <ul  class="nav navbar-nav" style="float:right;">
                        <li>@Html.ActionLink("Login", "Login", "Registration")</li>
                    </ul>
                </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - COETL</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>